version: "3.1"

services:
  db: 
    image: postgress:15
    restart: always
    environment:
      POSTGRESS_USER: postgress
      POSTGRESS_PASSWORD: postgress
      POSTGRESS_DB: news_bot
      PGDATA: /var/lib/postgresql/data/
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data/

  
volumes:
  db: